### ISSUE TITLE
Problems when reproducing the results

### ISSUE THREAD

**Issue by ChengenXie** [hustvl/VAD#21]
Hi, thanks for your great work and open-source code!
I've met some problems when I try to reproduce the results with pre-trained weights, and I would love some advice and help from you.
I prepare the environment and dataset as required, and I download the .pth file provided. Then I use the command of evaluation, 
```
CUDA_VISIBLE_DEVICES=0 python tools/test.py projects/configs/VAD/VAD_base_stage_2.py ckpts/resnet50-19c8e357.pth --launcher none --eval bbox --tmpdir tmp
```
and I get an error,
```
WARNING!!!!, Only can be used for obtain inference speed!!!!
load checkpoint from local path: ckpts/resnet50-19c8e357.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: (a lot of keys)
missing keys in source state_dict: (a lot of keys)

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 5.3 task/s, elapsed: 1140s, ETA:     0sTraceback (most recent call last):
  File "tools/test.py", line 294, in <module>
    main()
  File "tools/test.py", line 274, in main
    print(dataset.evaluate(outputs['bbox_results'], **eval_kwargs))
  File "/cpfs01/user/xiechengen/VAD/projects/mmdet3d_plugin/datasets/nuscenes_vad_dataset.py", line 1786, in evaluate
    result_dict['ADE_'+cls] = all_metric_dict['ADE_'+cls] / all_metric_dict['cnt_ade_'+cls]
ZeroDivisionError: float division by zero
```
It seems like the .pth file is not compatible with the config file. I also tried the other five config files (VAD_base_e2e.py, VAD_stage_1.py, etc.), but the results are the same.
Since I'm a beginner in training models, my question may seem to be stupid 😿 . I'd appreciate it if you could let me know how to use the .pth file correctly.
Thanks a lot! 😃

**Comment by rb93dett** [comment]
Hi, if you want to reproduce results with the provided weights, please follow the instructions in this [doc](https://github.com/hustvl/VAD/blob/main/docs/train_eval.md) to adjust the `img_norm_cfg` in the config file. Besides, it seems that you only use the res50 weight for evaluation in your command:
```
CUDA_VISIBLE_DEVICES=0 python tools/test.py projects/configs/VAD/VAD_base_stage_2.py ckpts/resnet50-19c8e357.pth --launcher none --eval bbox --tmpdir tmp
```
it should be the provided VAD_base.pth. Please try again with the right config file and the pre-trained weight : )

**Comment by ChengenXie** [comment]
Thank you for your reply! 😄 
I apologize for getting the .pth file wrong; I didn't look at the front page carefully. Now I used VAD_base.pth and it loads the model correctly. But I encountered a new reported error:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cpfs01/user/xiechengen/opt/miniconda3/envs/vad/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/cpfs01/user/xiechengen/opt/miniconda3/envs/vad/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/cpfs01/user/xiechengen/VAD/projects/mmdet3d_plugin/datasets/map_utils/tpfp.py", line 338, in custom_tpfp_gen
    matrix = custom_polyline_score(
  File "/cpfs01/user/xiechengen/VAD/projects/mmdet3d_plugin/datasets/map_utils/tpfp_chamfer.py", line 257, in custom_polyline_score
    if o.intersects(pline):
AttributeError: 'numpy.int64' object has no attribute 'intersects'
"""
```
Have you encountered this error before?

**Comment by rb93dett** [comment]
I haven't encountered this error before, it seems like a numpy version problem. I suggest you check your numpy version and make sure it is the same as ours, you can refer to this file [requeirment.txt](https://github.com/hustvl/VAD/blob/main/requirements.txt).

**Comment by h-enomoto** [comment]
Hello @ChengenXie ,
I am also encountering the same error( #23 ).
Could you please tell me how to get the "VAD_base.pth"?
Also, how did you change the command?
Your assistance would be greatly appreciated.

**Comment by h-enomoto** [comment]
Hello,
I find "VAD_base.pth" by [Models](https://github.com/hustvl/VAD/tree/main#models).
I was able to resolve it myself.
Thank you.

**Comment by yuyuyuyuyuty** [comment]
Hello, I would like to ask why I can not use my own training pth file to test? I still get errors when I use my own pth training
