### ISSUE TITLE
Abnormal termination by visualization command.

### ISSUE THREAD

**Issue by h-enomoto** [hustvl/VAD#34]
Hello,
After I did this [response,](https://github.com/hustvl/VAD/issues/29#issuecomment-1778550912) I ran the visualization command.
However, the visualization did not work correctly.

```
(vad) user1@Dev-VAD1:~/VAD$ python tools/analysis_tools/visualization.py --result-path ./test/VAD_tiny_stage_2/Sat_Oct_28_02_13_15_2023/pts_bbox/results_nusc.pkl --save-path ./save/visualization/results4
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 29.044 seconds.
======
Reverse indexing ...
Done reverse indexing in 6.3 seconds.
======
  0%|                                                                                   | 8/6019 [00:23<4:43:24,  2.83s/it]/home/user1/VAD/projects/mmdet3d_plugin/core/bbox/structures/nuscenes_box.py:262: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  fut_coords = fut_coords[[mode_idx]]
 17%|█████████████▏                                                                | 1018/6019 [1:03:46<5:13:34,  3.76s/it]Exception ignored in: <function Image.__del__ at 0x7fb59db2a310>
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/vad/lib/python3.8/tkinter/__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fb59deaa9d0>
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/vad/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fb59deaa9d0>
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/vad/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fb59deaa9d0>
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/vad/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x7fb59deaa9d0>
Traceback (most recent call last):
  File "/home/user1/miniconda3/envs/vad/lib/python3.8/tkinter/__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Tcl_AsyncDelete: async handler deleted by the wrong thread
Aborted (core dumped)
```

I don't know the cause of this problem and would appreciate any help.
Thanks.

**Comment by MRYUjg** [comment]
Pls have you solved it
