### ISSUE TITLE
Issue with MMCV library 

### ISSUE THREAD

**Issue by chrissunny94** [hustvl/VAD#66]
```CUDA_VISIBLE_DEVICES=0 python tools/test.py projects/configs/VAD/VAD_base.py /path/to/ckpt.pth --launcher none --eval bbox --tmpdir tmp```

```
Traceback (most recent call last):
  File "tools/test.py", line 22, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/home/cthalia/.local/lib/python3.8/site-packages/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
```

**Comment by wyield** [comment]
You need to reinstall mmdetection3d and check that its version is not 0.17, then check that the corresponding dependencies are installed correctly

**Comment by wyield** [comment]
You need to reinstall mmdetection3d and check that its version is 0.17.1, then check that the corresponding dependencies are installed correctly
