### ISSUE TITLE
No module named 'projects.mmdet3d_plugin.models.utils.ckpt_convert'

### ISSUE THREAD

**Issue by yt7589** [hustvl/VAD#7]
When I try to train the model with these command:
`python -m torch.distributed.run --nproc_per_node=1 --master_port=2333 tools/train.py projects/configs/VAD/VAD_base_e2e.py --launcher pytorch --deterministic --work-dir ./work/outputs`
Please note that I have only one GPU card and there has no VAD_base.py so I change it to VAD_base_e2e.py. Everything else is the same as the official document. But it reported errors as below:

projects.mmdet3d_plugin  
Traceback (most recent call last):  
  File "tools/train.py", line 266, in <module>  
    main()  
  File "tools/train.py", line 132, in main  
    plg_lib = importlib.import_module(_module_path)  
  File "/mnt/10t/yantao/software/anaconda3/envs/maptr/lib/python3.8/importlib/__init__.py", line 127, in import_module  
    return _bootstrap._gcd_import(name[level:], package, level)  
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import  
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load  
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked  
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked  
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module  
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/__init__.py", line 1, in <module>  
    from .core.bbox.assigners.hungarian_assigner_3d import HungarianAssigner3D  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/core/bbox/assigners/__init__.py", line 2, in <module>  
    from .map_hungarian_assigner_3d import MapHungarianAssigner3D  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/core/bbox/assigners/map_hungarian_assigner_3d.py", line 10, in <module>  
    from projects.mmdet3d_plugin.VAD.utils.map_utils import (  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/VAD/__init__.py", line 1, in <module>  
    from .modules import *  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/VAD/modules/__init__.py", line 1, in <module>  
    from .transformer import PerceptionTransformer  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/VAD/modules/transformer.py", line 10, in <module>  
    from projects.mmdet3d_plugin.models.utils.visual import save_tensor  
  File "/mnt/10t/yantao/adev/p00/VAD/projects/mmdet3d_plugin/models/utils/__init__.py", line 6, in <module>  
    from .ckpt_convert import swin_convert  
ModuleNotFoundError: No module named 'projects.mmdet3d_plugin.models.utils.ckpt_convert'  
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5145) of binary:  
 /mnt/10t/yantao/software/anaconda3/envs/maptr/bin/python  
/mnt/10t/yantao/software/anaconda3/envs/maptr/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning:

**Comment by yt7589** [comment]
Update:
If I comment out line 6 in projects/mmdet3d_plugin/models/utils/__init__.py as below:
```python
from .bricks import run_time
from .grid_mask import GridMask
from .position_embedding import RelPositionEmbedding
from .visual import save_tensor
# from .ckpt_convert import swin_convert
from .embed import PatchEmbed
```
The training process could start successfully. Is ckpt_convert not used any more but forgot to delete it?

**Comment by rb93dett** [comment]
Yes, it's an experimental code, I delete the file but forget to delete the import code.
Thanks for pointing it out, I'll fix this bug in the next update.
